name: containers

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '44 4 * * 0'

permissions:
  contents: read

jobs:
  shmem_matrix:
    strategy:
      fail-fast: false
      matrix:
        shmem: [sos_ubuntu, sos_fedora, oshmem_ubuntu, oshmem_fedora, oshmpi_ubuntu, oshmpi_fedora, osss_ubuntu, osss_fedora]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker container
        run: docker build -t local docker/${{ matrix.shmem }}/
      - name: run shmem4py test-1
        run: docker run --shm-size=1g --ipc=host -v $PWD:/repo -w/repo local /bin/bash -c "source /venv/bin/activate && pip install . && make test-1 opt=-v"
      - name: run shmem4py test-2
        run: docker run --shm-size=1g --ipc=host -v $PWD:/repo -w/repo local /bin/bash -c "source /venv/bin/activate && pip install . && make test-2 opt=-v"
      - name: run shmem4py demo-test-1
        run: docker run --shm-size=1g --ipc=host -v $PWD:/repo -w/repo local /bin/bash -c "source /venv/bin/activate && pip install . && cd demo && make test-1 opt=-v"
      - name: run shmem4py demo-test-2
        run: docker run --shm-size=1g --ipc=host -v $PWD:/repo -w/repo local /bin/bash -c "source /venv/bin/activate && pip install . && cd demo && make test-2 opt=-v"
