name: native

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '33 3 * * 0'

permissions:
  contents: read

jobs:

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        mpi:
          - mpich
        py:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup MPI (${{ matrix.mpi }})
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}

    - name: Use Python ${{ matrix.py }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py }}
        architecture: x64

    - name: Setup oshmpi
      run: >
        git clone https://github.com/pmodels/oshmpi --recurse-submodules &&
        cd oshmpi &&
        ./autogen.sh &&
        ./configure CC=/usr/bin/mpicc CXX=/usr/bin/mpicxx --prefix=$HOME/oshmpi/install &&
        make -j && make install &&
        echo "${HOME}/oshmpi/install/bin" >> $GITHUB_PATH

    - name: Install
      run: python -m pip install .

    - name: Test - 1 process
      run: make test-1

    - name: Test - 2 processes
      run: make test-2

    - name: Demo - Test - 1 process
      run: cd demo && make test-1

    - name: Demo - Test - 2 processes
      run: cd demo && make test-2
